const PDFDocument = require('pdfkit');
const { HEURISTIC_CATEGORIES } = require('../config/scoring.config');

const SEVERITY_COLORS = {
  critical: '#dc2626',
  high: '#ea580c',
  medium: '#d97706',
  low: '#65a30d',
};

const CATEGORY_LABELS = {
  vulnerableDependencies: 'Vulnerable Dependencies',
  hardcodedSecrets: 'Hardcoded Secrets',
  injectionFlaws: 'Injection Flaws',
  xss: 'Cross-Site Scripting (XSS)',
  brokenAuthentication: 'Broken Authentication',
  securityMisconfiguration: 'Security Misconfiguration',
  insecureFileUploads: 'Insecure File Uploads',
  brokenAccessControl: 'Broken Access Control',
  sensitiveDataExposure: 'Sensitive Data Exposure',
};

/**
 * Generates a PDF report for a completed scan, mirroring the dashboard:
 * overall score + risk band, sub-score breakdown, findings grouped by
 * category (with a clear flag on heuristic-only categories).
 * Returns the PDFDocument stream directly — caller pipes it to the response.
 */
function generateScanPdf(scan, project) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  doc.fontSize(20).fillColor('#0f172a').text('SecureDev Security Report', { align: 'left' });
  doc.moveDown(0.2);
  doc.fontSize(11).fillColor('#475569').text(`Project: ${project?.name || 'Unknown project'}`);
  doc.text(`Scan completed: ${scan.completedAt ? new Date(scan.completedAt).toLocaleString() : 'N/A'}`);
  doc.moveDown(1);

  // Overall score block
  doc.rect(50, doc.y, 495, 90).fill('#f1f5f9');
  const scoreY = doc.y + 15;
  doc.fillColor('#0f172a').fontSize(36).text(String(scan.finalScore ?? 'N/A'), 65, scoreY);
  doc.fontSize(12).fillColor('#334155').text('/ 100', 65 + 70, scoreY + 18);
  doc.fontSize(16).fillColor(riskColor(scan.riskBand)).text(scan.riskBand || 'Unknown', 250, scoreY + 5);
  doc.fontSize(10).fillColor('#64748b').text(
    'Security Score = 0.30(Dependency) + 0.20(Auth) + 0.20(Secrets) + 0.20(OWASP) + 0.10(Config)',
    250,
    scoreY + 30,
    { width: 280 }
  );
  doc.moveDown(6);

  // Sub-scores
  doc.fillColor('#0f172a').fontSize(14).text('Sub-Score Breakdown', 50, doc.y);
  doc.moveDown(0.5);
  const subScores = scan.subScores || {};
  const subScoreLabels = {
    dependency: 'Dependency Security (30%)',
    authentication: 'Authentication (20%)',
    secrets: 'Secrets Detection (20%)',
    owaspCompliance: 'OWASP Compliance (20%)',
    configuration: 'Configuration (10%)',
  };
  Object.entries(subScoreLabels).forEach(([key, label]) => {
    doc.fontSize(10).fillColor('#334155').text(`${label}: ${subScores[key] ?? 'N/A'} / 100`);
  });
  doc.moveDown(1);

  // Engine status
  doc.fontSize(14).fillColor('#0f172a').text('Scan Engines');
  doc.moveDown(0.3);
  const engineStatus = scan.engineStatus || {};
  doc.fontSize(10).fillColor('#334155').text(`npm audit: ${engineStatus.npmAudit || 'unknown'}`);
  doc.text(`Secret scanner: ${engineStatus.secretScanner || 'unknown'}`);
  doc.text(`Semgrep: ${engineStatus.semgrep || 'unknown'}`);
  doc.moveDown(1);

  // Findings grouped by category
  doc.fontSize(14).fillColor('#0f172a').text('Findings by Category');
  doc.moveDown(0.3);

  const findings = scan.findings || [];
  const byCategory = {};
  for (const f of findings) {
    if (!byCategory[f.category]) byCategory[f.category] = [];
    byCategory[f.category].push(f);
  }

  if (findings.length === 0) {
    doc.fontSize(10).fillColor('#64748b').text('No findings detected.');
  }

  for (const [category, catFindings] of Object.entries(byCategory)) {
    doc.moveDown(0.5);
    const label = CATEGORY_LABELS[category] || category;
    const isHeuristic = HEURISTIC_CATEGORIES.includes(category);
    doc.fontSize(12).fillColor('#0f172a').text(`${label}${isHeuristic ? '  (heuristic — not exhaustive)' : ''}`);

    catFindings.forEach((f) => {
      doc.fontSize(9).fillColor(SEVERITY_COLORS[f.severity] || '#334155').text(
        `[${f.severity.toUpperCase()}] ${f.title}`,
        { continued: false }
      );
      doc.fontSize(9).fillColor('#64748b').text(
        `${f.file || 'N/A'}${f.line ? `:${f.line}` : ''} — ${f.description}`,
        { indent: 10 }
      );
    });
  }

  doc.moveDown(1);
  doc.fontSize(8).fillColor('#94a3b8').text(
    'Generated by SecureDev. Insecure File Uploads, Broken Access Control, and Sensitive Data Exposure findings ' +
      'are produced by lightweight pattern-based heuristics, not exhaustive static/dataflow analysis — verify manually.',
    { width: 495 }
  );

  doc.end();
  return doc;
}

function riskColor(band) {
  if (band === 'Low Risk') return '#16a34a';
  if (band === 'Medium Risk') return '#d97706';
  if (band === 'High Risk') return '#ea580c';
  if (band === 'Critical Risk') return '#dc2626';
  return '#334155';
}

module.exports = { generateScanPdf };
